const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('cs', {
  loadState: () => ipcRenderer.invoke('state:load'),
  saveState: (s) => ipcRenderer.invoke('state:save', s),
  version: () => ipcRenderer.invoke('app:version'),
  openExternal: (u) => ipcRenderer.invoke('shell:open', u),
  updateMode: () => ipcRenderer.invoke('update:mode'),
  updateCheck: () => ipcRenderer.invoke('update:check'),
  updateInstall: () => ipcRenderer.invoke('update:install'),
  onUpdateEvent: (cb) => ipcRenderer.on('update:event', (e, d) => cb(d)),
  installCable: () => ipcRenderer.invoke('cable:install'),
  log: (m) => ipcRenderer.invoke('log:write', m),
  logPath: () => ipcRenderer.invoke('log:path'),
  sendLog: (pin) => ipcRenderer.invoke('log:send', pin),
  saveCapture: (buf) => ipcRenderer.invoke('rec:save', buf),
  changelog: () => ipcRenderer.invoke('changelog:get'),
  onHotkey: (cb) => ipcRenderer.on('hotkey', (e, k) => cb(k)),
  muteState: (m) => ipcRenderer.invoke('mute:state', m),
  renameMic: (from, to, flow, adapter) => ipcRenderer.invoke('mic:rename', from, to, flow, adapter),
  audioDefaults: () => ipcRenderer.invoke('audio:defaults'),
  audioSetDefault: (name, adapter) => ipcRenderer.invoke('audio:setDefault', name, adapter),
  audioOutGet: () => ipcRenderer.invoke('audio:outGet'),
  audioOutList: () => ipcRenderer.invoke('audio:outList'),
  audioOutSet: (id) => ipcRenderer.invoke('audio:outSet', id),
  audioFormats: () => ipcRenderer.invoke('audio:formats'),
  audioSetFormat: (name, adapter, flow, rate) => ipcRenderer.invoke('audio:setFormat', name, adapter, flow, rate),
  rememberDefault: (prev, want) => ipcRenderer.invoke('audio:remember', prev, want),
  getAutostart: () => ipcRenderer.invoke('autostart:get'),
  setAutostart: (on) => ipcRenderer.invoke('autostart:set', on),
  onCableProgress: (cb) => ipcRenderer.on('cable:progress', (e, s) => cb(s)),
  minimize: () => ipcRenderer.invoke('win:minimize'),
  zoom: (f) => ipcRenderer.invoke('win:zoom', f),
  compact: (on) => ipcRenderer.invoke('win:compact', on),
  trayIcon: (d) => ipcRenderer.invoke('tray:icon', d),
  close: () => ipcRenderer.invoke('win:close')
});
